import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({
  connectionString: process.env.DIRECT_URL ?? process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

const SEED_ROASTERS = [
  {
    name: "Onyx Coffee Lab",
    slug: "onyx-coffee-lab",
    description: "Pushing the boundaries of specialty coffee through science and transparency. Every bean is selected, profiled, and roasted with precision to unlock its full potential.",
    country: "United States",
    countryCode: "US",
    city: "Rogers, Arkansas",
    lat: 36.332,
    lng: -94.118,
    website: "https://onyxcoffeelab.com",
    shopUrl: "https://onyxcoffeelab.com/collections",
    instagram: "onyxcoffeelab",
    email: "hello@onyxcoffeelab.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    imageAlt: "Onyx Coffee Lab interior",
  },
  {
    name: "Tim Wendelboe",
    slug: "tim-wendelboe",
    description: "An espresso bar, roastery and coffee resource center focusing on quality. Founded by World Barista Champion Tim Wendelboe in Oslo.",
    country: "Norway",
    countryCode: "NO",
    city: "Oslo",
    lat: 59.916,
    lng: 10.752,
    website: "https://timwendelboe.no",
    shopUrl: "https://timwendelboe.no/shop",
    instagram: "timaborgen",
    email: "post@timwendelboe.no",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Colombia", "Kenya", "Ethiopia"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop",
    imageAlt: "Tim Wendelboe barista",
  },
  {
    name: "Square Mile",
    slug: "square-mile-coffee",
    description: "A multi-award winning specialty coffee roasting company founded in 2008 by James Hoffmann and Anette Moldvaer.",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    lat: 51.507,
    lng: -0.127,
    website: "https://squaremilecoffee.com",
    shopUrl: "https://squaremilecoffee.com/collections",
    instagram: "squaremilecoffee",
    email: "info@squaremilecoffee.com",
    certifications: ["DIRECT_TRADE", "ORGANIC", "SCA_MEMBER"],
    origins: ["Ethiopia", "Kenya", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=600&fit=crop",
    imageAlt: "Square Mile coffee bags",
  },
  {
    name: "Hard Beans",
    slug: "hard-beans-opole",
    description: "Born in Opole, Hard Beans represents the pinnacle of Polish specialty coffee craftsmanship. Our approach is purely scientific yet deeply sensorial.",
    country: "Poland",
    countryCode: "PL",
    city: "Opole",
    lat: 50.675,
    lng: 17.921,
    website: "https://hardbeans.pl",
    shopUrl: "https://hardbeans.pl/sklep",
    instagram: "hardbeansroastery",
    email: "hello@hardbeans.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Kenya", "Colombia"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&auto=format&fit=crop",
    imageAlt: "Hard Beans roastery",
  },
  {
    name: "Gardelli Specialty",
    slug: "gardelli-specialty",
    description: "Founded by World Coffee Roasting Champion Rubens Gardelli. Dedicated to sourcing and roasting the finest specialty coffees.",
    country: "Italy",
    countryCode: "IT",
    city: "Forlì",
    lat: 44.222,
    lng: 12.040,
    website: "https://gardellicoffee.com",
    shopUrl: "https://gardellicoffee.com/shop",
    instagram: "gardellicoffee",
    email: "info@gardellicoffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Panama", "Colombia"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop",
    imageAlt: "Gardelli roasting machine",
  },
  {
    name: "Assembly Coffee",
    slug: "assembly-coffee",
    description: "A roastery dedicated to the pursuit of independent coffee excellence. Sourcing directly from producers worldwide.",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    lat: 51.461,
    lng: -0.115,
    website: "https://assemblycoffee.co.uk",
    shopUrl: "https://assemblycoffee.co.uk/shop",
    instagram: "assemblycoffee",
    email: "hello@assemblycoffee.co.uk",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia", "Colombia", "Rwanda"],
    roastStyles: ["Light", "Filter", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&h=600&fit=crop",
    imageAlt: "Assembly Coffee beans",
  },
  {
    name: "HAYB Coffee",
    slug: "hayb-coffee",
    description: "Warsaw-based specialty roaster known for innovative processing methods and direct relationships with farmers across Africa and South America.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.229,
    lng: 21.012,
    website: "https://haybcoffee.pl",
    shopUrl: "https://haybcoffee.pl/shop",
    instagram: "haybcoffee",
    email: "hello@haybcoffee.pl",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop",
    imageAlt: "HAYB Coffee shop",
  },
  {
    name: "Coffee Proficiency",
    slug: "coffee-proficiency",
    description: "Kraków-based micro-roastery combining scientific precision with artisanal craft. Specializing in competition-grade lots.",
    country: "Poland",
    countryCode: "PL",
    city: "Kraków",
    lat: 50.064,
    lng: 19.944,
    website: "https://coffeeproficiency.com",
    shopUrl: "https://coffeeproficiency.com/shop",
    instagram: "coffeeproficiency",
    email: "info@coffeeproficiency.com",
    certifications: ["SCA_MEMBER", "DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Peru"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&auto=format&fit=crop",
    imageAlt: "Coffee Proficiency roastery",
  },
  {
    name: "The Nordic Roast",
    slug: "the-nordic-roast",
    description: "Oslo-based roastery focused on sustainability and light roasts that showcase terroir. Working directly with smallholder farmers.",
    country: "Norway",
    countryCode: "NO",
    city: "Oslo",
    lat: 59.930,
    lng: 10.738,
    website: "https://thenordicroast.no",
    shopUrl: "https://thenordicroast.no/shop",
    instagram: "nordicroast",
    email: "hello@thenordicroast.no",
    certifications: ["ORGANIC", "DIRECT_TRADE", "FAIR_TRADE"],
    origins: ["Ethiopia", "Kenya", "Rwanda"],
    roastStyles: ["Light"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&h=600&fit=crop",
    imageAlt: "Nordic Roast barista",
  },
  {
    name: "Dark Matter Labs",
    slug: "dark-matter-labs",
    description: "Chicago's experimental roastery pushing the boundaries of flavor. Known for bold, innovative blends and single origins.",
    country: "United States",
    countryCode: "US",
    city: "Chicago",
    lat: 41.878,
    lng: -87.629,
    website: "https://darkmatterlabs.com",
    shopUrl: "https://darkmatterlabs.com/shop",
    instagram: "darkmatterlabs",
    email: "hello@darkmatterlabs.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Colombia", "Ethiopia", "Indonesia"],
    roastStyles: ["Medium", "Dark", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&h=600&fit=crop",
    imageAlt: "Dark Matter Labs roasting",
  },
  {
    name: "Flora & Fauna",
    slug: "flora-and-fauna",
    description: "Melbourne-based ethical roastery committed to sustainable sourcing and community building through exceptional coffee.",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    lat: -37.813,
    lng: 144.963,
    website: "https://floraandfauna.coffee",
    shopUrl: "https://floraandfauna.coffee/shop",
    instagram: "florafaunacoffee",
    email: "hello@floraandfauna.coffee",
    certifications: ["ORGANIC", "FAIR_TRADE", "DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&h=600&fit=crop",
    imageAlt: "Flora & Fauna coffee",
  },
  {
    name: "Sey Coffee",
    slug: "sey-coffee",
    description: "Clean, expressive, and terroir-driven coffee roasting from Brooklyn. Each coffee is roasted to express the unique character of its origin.",
    country: "United States",
    countryCode: "US",
    city: "Brooklyn",
    lat: 40.678,
    lng: -73.944,
    website: "https://www.seycoffee.com",
    shopUrl: "https://www.seycoffee.com/collections",
    instagram: "seycoffee",
    email: "hello@seycoffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop",
    imageAlt: "Sey Coffee cup",
  },
  // --- Germany (4) ---
  {
    name: "The Barn",
    slug: "the-barn-berlin",
    description: "One of the first specialty coffee pioneers in Germany, known for ultra-light roasts that highlight terroir and origin character.",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    lat: 52.529,
    lng: 13.413,
    website: "https://thebarn.de",
    shopUrl: "https://thebarn.de/collections",
    instagram: "thebarn",
    email: "info@thebarn.de",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=600&fit=crop",
    imageAlt: "The Barn coffee roastery Berlin",
  },
  {
    name: "Five Elephant",
    slug: "five-elephant",
    description: "Berlin-based roastery with a strong emphasis on sustainability and direct trade. Combining specialty coffee with artisan cake.",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    lat: 52.489,
    lng: 13.430,
    website: "https://fiveelephant.com",
    shopUrl: "https://fiveelephant.com/shop",
    instagram: "fiveelephant",
    email: "hello@fiveelephant.com",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia", "Colombia", "Brazil"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&h=600&fit=crop",
    imageAlt: "Five Elephant roastery",
  },
  {
    name: "Bonanza Coffee Roasters",
    slug: "bonanza-coffee",
    description: "Berlin roastery and café with a strong presence in the city's specialty scene. Known for quality single origins and expertly crafted blends.",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    lat: 52.530,
    lng: 13.404,
    website: "https://bonanzacoffee.de",
    shopUrl: "https://bonanzacoffee.de/shop",
    instagram: "bonanzacoffee",
    email: "info@bonanzacoffee.de",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&h=600&fit=crop",
    imageAlt: "Bonanza Coffee Berlin",
  },
  {
    name: "19grams Coffee Roasters",
    slug: "19grams-coffee",
    description: "Berlin-based roasters committed to transparency and single-origin excellence. Active in SCA community with strong content and education focus.",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    lat: 52.507,
    lng: 13.454,
    website: "https://19grams.de",
    shopUrl: "https://19grams.de/shop",
    instagram: "19grams",
    email: "hello@19grams.de",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya", "Rwanda"],
    roastStyles: ["Light", "Medium", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&auto=format&fit=crop",
    imageAlt: "19grams coffee roasting",
  },
  // --- Poland (6 additional) ---
  {
    name: "JAVA Coffee Roasters",
    slug: "java-coffee-roasters",
    description: "One of the oldest specialty roasters in Poland, founded in 2001. Award-winning single origins and multi-origin blends with strong B2B presence.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.232,
    lng: 21.006,
    website: "https://javacoffee.pl",
    shopUrl: "https://javacoffee.pl/en/shop",
    instagram: "javacoffeeroasters",
    email: "info@javacoffee.pl",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Brazil", "Guatemala"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    imageAlt: "JAVA Coffee Roasters Warsaw",
  },
  {
    name: "Etno Cafe",
    slug: "etno-cafe",
    description: "A pioneer of specialty coffee in Poland based in Wrocław. Direct trade relationships, strong community, and popular subscription service.",
    country: "Poland",
    countryCode: "PL",
    city: "Wrocław",
    lat: 51.107,
    lng: 17.038,
    website: "https://etnocafe.pl",
    shopUrl: "https://etnocafe.pl/sklep",
    instagram: "etnocafe",
    email: "info@etnocafe.pl",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia", "Colombia", "Peru", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop",
    imageAlt: "Etno Cafe roastery",
  },
  {
    name: "Story Coffee Roasters",
    slug: "story-coffee-roasters",
    description: "Warsaw-based craft roastery focused on careful bean selection and freshness. Each coffee tells a story from farm to cup.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.237,
    lng: 21.017,
    website: "https://storycoffee.pl",
    shopUrl: "https://storycoffee.pl/en/shop",
    instagram: "storycoffeeroasters",
    email: "hello@storycoffee.pl",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&h=600&fit=crop",
    imageAlt: "Story Coffee Roasters",
  },
  {
    name: "CoffeeLab",
    slug: "coffeelab-warszawa",
    description: "Roastery and coffee school in Warsaw. Training baristas and Q-Graders while roasting exceptional single-origin coffees.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.225,
    lng: 21.003,
    website: "https://coffeelab.pl",
    shopUrl: "https://coffeelab.pl/sklep",
    instagram: "coffeelab.pl",
    email: "info@coffeelab.pl",
    certifications: ["SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Peru"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop",
    imageAlt: "CoffeeLab Warsaw",
  },
  {
    name: "Milo Coffee Roasters",
    slug: "milo-coffee-roasters",
    description: "Polish roaster with a Scandinavian-influenced light roasting style. Strong online presence and commitment to filter coffee excellence.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.240,
    lng: 21.020,
    website: "https://miloroast.com",
    shopUrl: "https://miloroast.com/shop",
    instagram: "miloroast",
    email: "hello@miloroast.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Colombia"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&h=600&fit=crop",
    imageAlt: "Milo Coffee Roasters",
  },
  {
    name: "Sheep and Raven",
    slug: "sheep-and-raven",
    description: "Warsaw micro-roastery specializing in experimental micro-batches and filter coffee. Exceptionally high quality with ratings above 4.5/5.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.228,
    lng: 21.015,
    website: null,
    shopUrl: null,
    instagram: "sheepandraven",
    email: null,
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Colombia", "Rwanda"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop",
    imageAlt: "Sheep and Raven coffee",
  },
  // --- Denmark (3) ---
  {
    name: "La Cabra Coffee Roasters",
    slug: "la-cabra",
    description: "Aarhus-based roastery known for elegant light roasts and frequent visits to coffee producers. Strong branding and design-forward approach.",
    country: "Denmark",
    countryCode: "DK",
    city: "Aarhus",
    lat: 56.162,
    lng: 10.203,
    website: "https://lacabra.dk",
    shopUrl: "https://lacabra.dk/shop",
    instagram: "lacabracoffee",
    email: "info@lacabra.dk",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    imageAlt: "La Cabra Coffee Roasters",
  },
  {
    name: "Coffee Collective",
    slug: "coffee-collective",
    description: "Copenhagen pioneers of transparent pricing — publishing exactly how much they pay farmers. Direct trade at 2-3x market prices.",
    country: "Denmark",
    countryCode: "DK",
    city: "Copenhagen",
    lat: 55.676,
    lng: 12.568,
    website: "https://coffeecollective.dk",
    shopUrl: "https://coffeecollective.dk/shop",
    instagram: "coffeecollective",
    email: "info@coffeecollective.dk",
    certifications: ["DIRECT_TRADE", "FAIR_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop",
    imageAlt: "Coffee Collective Copenhagen",
  },
  {
    name: "April Coffee Roasters",
    slug: "april-coffee",
    description: "Copenhagen-based roaster with a strong competition presence in SCA events. Nordic-style light roasts recognized across Europe and Japan.",
    country: "Denmark",
    countryCode: "DK",
    city: "Copenhagen",
    lat: 55.683,
    lng: 12.572,
    website: "https://april.coffee",
    shopUrl: "https://april.coffee/shop",
    instagram: "aprilcoffeeroasters",
    email: "hello@april.coffee",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=600&fit=crop",
    imageAlt: "April Coffee Roasters",
  },
  // --- Sweden (2) ---
  {
    name: "Drop Coffee Roasters",
    slug: "drop-coffee",
    description: "Stockholm roastery active in Cup of Excellence competitions with ~€3M revenue. Known for precise single-origin filter coffees.",
    country: "Sweden",
    countryCode: "SE",
    city: "Stockholm",
    lat: 59.329,
    lng: 18.068,
    website: "https://dropcoffee.se",
    shopUrl: "https://dropcoffee.se/shop",
    instagram: "dropcoffee",
    email: "info@dropcoffee.se",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&h=600&fit=crop",
    imageAlt: "Drop Coffee Roasters Stockholm",
  },
  {
    name: "Koppi",
    slug: "koppi-helsingborg",
    description: "Helsingborg roastery with multiple Swedish Barista Championship titles. Nordic light roast philosophy with direct farm relationships.",
    country: "Sweden",
    countryCode: "SE",
    city: "Helsingborg",
    lat: 56.046,
    lng: 12.694,
    website: "https://koppi.se",
    shopUrl: "https://koppi.se/shop",
    instagram: "koppiroasters",
    email: "hello@koppi.se",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Colombia"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&h=600&fit=crop",
    imageAlt: "Koppi coffee roastery",
  },
  // --- Netherlands (2) ---
  {
    name: "DAK Coffee Roasters",
    slug: "dak-coffee",
    description: "Amsterdam roastery founded in 2019. Named after the Dutch word for 'roof', focused on competition-grade single origins.",
    country: "Netherlands",
    countryCode: "NL",
    city: "Amsterdam",
    lat: 52.370,
    lng: 4.895,
    website: "https://dakcoffeeroasters.com",
    shopUrl: "https://dakcoffeeroasters.com/shop",
    instagram: "dakcoffeeroasters",
    email: "info@dakcoffeeroasters.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&auto=format&fit=crop",
    imageAlt: "DAK Coffee Roasters Amsterdam",
  },
  {
    name: "Friedhats Coffee Roasters",
    slug: "friedhats-coffee",
    description: "Amsterdam-based roasters with numerous Cup of Excellence medals. Specializing in competition-grade filter coffee.",
    country: "Netherlands",
    countryCode: "NL",
    city: "Amsterdam",
    lat: 52.366,
    lng: 4.899,
    website: "https://friedhats.com",
    shopUrl: "https://friedhats.com/shop",
    instagram: "friedhats",
    email: "info@friedhats.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&h=600&fit=crop",
    imageAlt: "Friedhats Coffee Roasters",
  },
  // --- France (2) ---
  {
    name: "L'Arbre à Café",
    slug: "larbre-a-cafe",
    description: "Paris-based leader of French specialty coffee. Owner Hippolyte Courty is known for origin expeditions and direct trade relationships.",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    lat: 48.856,
    lng: 2.352,
    website: "https://larbreacafe.com",
    shopUrl: "https://larbreacafe.com/boutique",
    instagram: "larbreacafe",
    email: "contact@larbreacafe.com",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Brazil"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop",
    imageAlt: "L'Arbre à Café Paris",
  },
  {
    name: "Café Lomi",
    slug: "cafe-lomi",
    description: "Paris roastery and barista training center. Nordic-influenced roasting with collaborations with Michelin-starred restaurants.",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    lat: 48.889,
    lng: 2.349,
    website: "https://cafelomi.com",
    shopUrl: "https://cafelomi.com/boutique",
    instagram: "cafelomi",
    email: "hello@cafelomi.com",
    certifications: ["SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&auto=format&fit=crop",
    imageAlt: "Café Lomi Paris",
  },
  // --- Czech Republic (1) ---
  {
    name: "Mazelab Coffee Roasters",
    slug: "mazelab-coffee",
    description: "Prague-based roastery combining a coffee lab with a photography gallery. Sensory-focused approach to aromatic profiles.",
    country: "Czech Republic",
    countryCode: "CZ",
    city: "Prague",
    lat: 50.075,
    lng: 14.437,
    website: "https://mazelabcoffee.com",
    shopUrl: "https://mazelabcoffee.com/shop",
    instagram: "mazelabcoffee",
    email: "info@mazelabcoffee.com",
    certifications: [],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&h=600&fit=crop",
    imageAlt: "Mazelab Coffee Prague",
  },
  // --- UK (2 additional) ---
  {
    name: "Origin Coffee",
    slug: "origin-coffee",
    description: "Best Roaster in Europe 2025 (Global Coffee Awards) and Most Sustainable Brand. Direct trade from Cornwall to the world.",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Truro",
    lat: 50.263,
    lng: -5.051,
    website: "https://origincoffee.co.uk",
    shopUrl: "https://origincoffee.co.uk/collections",
    instagram: "origincoffee",
    email: "hello@origincoffee.co.uk",
    certifications: ["DIRECT_TRADE", "ORGANIC", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Brazil", "Guatemala"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop",
    imageAlt: "Origin Coffee roastery",
  },
  {
    name: "Workshop Coffee",
    slug: "workshop-coffee",
    description: "London roastery and café chain with B2B wholesale. Direct trade single-origin espresso and filter.",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    lat: 51.520,
    lng: -0.109,
    website: "https://workshopcoffee.com",
    shopUrl: "https://workshopcoffee.com/shop",
    instagram: "workshopcoffee",
    email: "hello@workshopcoffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop",
    imageAlt: "Workshop Coffee London",
  },
  // --- USA (4 additional) ---
  {
    name: "Utopian Coffee",
    slug: "utopian-coffee",
    description: "Overall Winner — Global Coffee Awards US & Canada 2025. Exclusively sourcing from regenerative agriculture farms.",
    country: "United States",
    countryCode: "US",
    city: "Fort Wayne, Indiana",
    lat: 41.079,
    lng: -85.139,
    website: "https://utopiancoffee.com",
    shopUrl: "https://utopiancoffee.com/shop",
    instagram: "utopiancoffee",
    email: "hello@utopiancoffee.com",
    certifications: ["DIRECT_TRADE", "ORGANIC", "FAIR_TRADE"],
    origins: ["Colombia", "Ethiopia", "Guatemala"],
    roastStyles: ["Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    imageAlt: "Utopian Coffee roastery",
  },
  {
    name: "Counter Culture Coffee",
    slug: "counter-culture",
    description: "B Corp certified pioneer of direct trade in the US. Leader in barista education and sustainability transparency.",
    country: "United States",
    countryCode: "US",
    city: "Durham, North Carolina",
    lat: 35.994,
    lng: -78.898,
    website: "https://counterculturecoffee.com",
    shopUrl: "https://counterculturecoffee.com/shop",
    instagram: "counterculturecoffee",
    email: "info@counterculturecoffee.com",
    certifications: ["DIRECT_TRADE", "ORGANIC", "FAIR_TRADE", "SCA_MEMBER"],
    origins: ["Colombia", "Ethiopia", "Guatemala", "Kenya"],
    roastStyles: ["Light", "Medium", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop",
    imageAlt: "Counter Culture Coffee",
  },
  {
    name: "Intelligentsia Coffee",
    slug: "intelligentsia-coffee",
    description: "Co-founder of the third wave coffee movement. Direct trade espresso and filter from Chicago since 1995.",
    country: "United States",
    countryCode: "US",
    city: "Chicago, Illinois",
    lat: 41.886,
    lng: -87.647,
    website: "https://intelligentsiacoffee.com",
    shopUrl: "https://intelligentsiacoffee.com/collections",
    instagram: "intelligentsiacoffee",
    email: "info@intelligentsiacoffee.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Brazil", "Guatemala"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=600&fit=crop",
    imageAlt: "Intelligentsia Coffee Chicago",
  },
  {
    name: "Stumptown Coffee Roasters",
    slug: "stumptown-coffee",
    description: "Portland-based pioneer of direct trade in the US. One of the original third wave roasters, known for bold single origins and blends.",
    country: "United States",
    countryCode: "US",
    city: "Portland, Oregon",
    lat: 45.523,
    lng: -122.676,
    website: "https://stumptowncoffee.com",
    shopUrl: "https://stumptowncoffee.com/collections",
    instagram: "stumptowncoffee",
    email: "info@stumptowncoffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Indonesia"],
    roastStyles: ["Medium", "Espresso", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&h=600&fit=crop",
    imageAlt: "Stumptown Coffee Roasters Portland",
  },
  // --- Canada (1) ---
  {
    name: "Phil & Sebastian",
    slug: "phil-and-sebastian",
    description: "Calgary-based roaster, Gold winner for washed espresso at Global Coffee Awards 2025. Chain of cafés across Alberta.",
    country: "Canada",
    countryCode: "CA",
    city: "Calgary, Alberta",
    lat: 51.044,
    lng: -114.071,
    website: "https://philsebastian.com",
    shopUrl: "https://philsebastian.com/collections",
    instagram: "philandsebastian",
    email: "hello@philsebastian.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&h=600&fit=crop",
    imageAlt: "Phil & Sebastian Calgary",
  },
  // --- Australia (2 additional) ---
  {
    name: "Market Lane Coffee",
    slug: "market-lane-coffee",
    description: "Leader of Melbourne's specialty scene with detailed origin transparency. Known for precise single-origin filter and espresso.",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    lat: -37.799,
    lng: 144.968,
    website: "https://marketlane.com.au",
    shopUrl: "https://marketlane.com.au/collections",
    instagram: "marketlanecoffee",
    email: "hello@marketlane.com.au",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya", "Guatemala"],
    roastStyles: ["Light", "Filter", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop",
    imageAlt: "Market Lane Coffee Melbourne",
  },
  {
    name: "Toby's Estate",
    slug: "tobys-estate",
    description: "#1 in World's 100 Best Coffee Shops 2025. Founded in 2001, exporting specialty to Japan and Asia.",
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    lat: -33.868,
    lng: 151.207,
    website: "https://tobysestate.com.au",
    shopUrl: "https://tobysestate.com.au/shop",
    instagram: "tobysestate",
    email: "hello@tobysestate.com.au",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&h=600&fit=crop",
    imageAlt: "Toby's Estate Sydney",
  },
  // --- Japan (3) ---
  {
    name: "Kurasu Kyoto",
    slug: "kurasu-kyoto",
    description: "Kyoto-based roaster with Nordic-influenced single origins. Strong international online sales and subscription service.",
    country: "Japan",
    countryCode: "JP",
    city: "Kyoto",
    lat: 35.011,
    lng: 135.768,
    website: "https://kurasu.kyoto",
    shopUrl: "https://kurasu.kyoto/collections",
    instagram: "kurasucoffee",
    email: "hello@kurasu.kyoto",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop",
    imageAlt: "Kurasu Kyoto coffee",
  },
  {
    name: "Fuglen Coffee Roasters",
    slug: "fuglen-coffee",
    description: "Norwegian concept transplanted to Tokyo. Nordic roasting philosophy with a dual-culture brand spanning Oslo and Japan.",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    lat: 35.660,
    lng: 139.666,
    website: "https://fuglen.com",
    shopUrl: "https://fuglen.com/shop",
    instagram: "fuglencoffee",
    email: "hello@fuglen.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&h=600&fit=crop",
    imageAlt: "Fuglen Coffee Tokyo",
  },
  {
    name: "Takamura Coffee Roasters",
    slug: "takamura-coffee",
    description: "Iconic Osaka roastery known for precision roasting. Also operates a specialty brewing tools shop.",
    country: "Japan",
    countryCode: "JP",
    city: "Osaka",
    lat: 34.693,
    lng: 135.502,
    website: "https://en.takamura-coffee.com",
    shopUrl: "https://en.takamura-coffee.com/shop",
    instagram: "takamura_coffee",
    email: "info@takamura-coffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Kenya"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop",
    imageAlt: "Takamura Coffee Roasters Osaka",
  },
  // --- Ethiopia (2) ---
  {
    name: "Garden of Coffee",
    slug: "garden-of-coffee",
    description: "Traditional Ethiopian hand-roasting from Addis Ababa. Export and local cafés bringing authentic origin coffee to the world.",
    country: "Ethiopia",
    countryCode: "ET",
    city: "Addis Ababa",
    lat: 9.025,
    lng: 38.747,
    website: "https://gardenofcoffee.com",
    shopUrl: null,
    instagram: "gardenofcoffee",
    email: "info@gardenofcoffee.com",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia"],
    roastStyles: ["Light", "Medium", "Dark"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop",
    imageAlt: "Garden of Coffee Addis Ababa",
  },
  {
    name: "Tomoca Coffee",
    slug: "tomoca-coffee",
    description: "Iconic Ethiopian roastery founded in 1953. The oldest and most famous coffee house in Addis Ababa.",
    country: "Ethiopia",
    countryCode: "ET",
    city: "Addis Ababa",
    lat: 9.030,
    lng: 38.750,
    website: "https://tomocacoffee.com",
    shopUrl: null,
    instagram: "tomocacoffee",
    email: null,
    certifications: [],
    origins: ["Ethiopia"],
    roastStyles: ["Medium", "Dark", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop",
    imageAlt: "Tomoca Coffee Addis Ababa",
  },
  // --- Kenya (2) ---
  {
    name: "Vava Coffee",
    slug: "vava-coffee",
    description: "Nairobi-based since 2009 with a mission to decolonize the coffee trade. Direct access for roasters and consumers worldwide.",
    country: "Kenya",
    countryCode: "KE",
    city: "Nairobi",
    lat: -1.286,
    lng: 36.817,
    website: "https://vavacoffeeinc.com",
    shopUrl: "https://vavacoffeeinc.com/shop",
    instagram: "vavacoffee",
    email: "info@vavacoffeeinc.com",
    certifications: ["DIRECT_TRADE", "FAIR_TRADE"],
    origins: ["Kenya", "Ethiopia", "Rwanda"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    imageAlt: "Vava Coffee Nairobi",
  },
  {
    name: "Connect Coffee Roasters",
    slug: "connect-coffee",
    description: "Nairobi roastery with daily on-site roasting and strong relationships with local Kenyan farmers.",
    country: "Kenya",
    countryCode: "KE",
    city: "Nairobi",
    lat: -1.292,
    lng: 36.821,
    website: "https://connectcoffeeroasters.net",
    shopUrl: null,
    instagram: "connectcoffee",
    email: "info@connectcoffeeroasters.net",
    certifications: ["DIRECT_TRADE"],
    origins: ["Kenya"],
    roastStyles: ["Light", "Medium", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop",
    imageAlt: "Connect Coffee Roasters Nairobi",
  },
  // --- Brazil (2) ---
  {
    name: "O'Coffee Brazilian Estates",
    slug: "ocoffee-brazil",
    description: "São Paulo roastery with 7 million coffee trees. Direct trade to 15+ countries with a wide range of specialty profiles.",
    country: "Brazil",
    countryCode: "BR",
    city: "São Paulo",
    lat: -23.550,
    lng: -46.633,
    website: "https://ocoffee.com.br",
    shopUrl: "https://ocoffee.com.br/loja",
    instagram: "ocoffeebrazil",
    email: "contato@ocoffee.com.br",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Brazil"],
    roastStyles: ["Medium", "Dark", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=600&fit=crop",
    imageAlt: "O'Coffee Brazilian Estates",
  },
  {
    name: "Academia do Café",
    slug: "academia-do-cafe",
    description: "Belo Horizonte roastery and SCA-licensed coffee school. A center of specialty education in Brazil.",
    country: "Brazil",
    countryCode: "BR",
    city: "Belo Horizonte",
    lat: -19.919,
    lng: -43.938,
    website: "https://academiadocafe.com.br",
    shopUrl: "https://academiadocafe.com.br/loja",
    instagram: "academiadocafe",
    email: "contato@academiadocafe.com.br",
    certifications: ["SCA_MEMBER"],
    origins: ["Brazil", "Colombia"],
    roastStyles: ["Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&h=600&fit=crop",
    imageAlt: "Academia do Café Belo Horizonte",
  },
];

async function main() {
  console.log("Seeding database...");

  for (const roaster of SEED_ROASTERS) {
    const { imageUrl, imageAlt, ...data } = roaster;

    const created = await prisma.roaster.upsert({
      where: { slug: data.slug },
      update: data,
      create: {
        ...data,
        verifiedAt: new Date(),
        images: {
          create: {
            url: imageUrl,
            alt: imageAlt,
            order: 0,
            isPrimary: true,
          },
        },
      },
    });

    console.log(`  ${created.status === "VERIFIED" ? "✓" : "○"} ${created.name} (${created.slug})`);
  }

  console.log(`\nSeeded ${SEED_ROASTERS.length} roasters.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
