import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({
  connectionString: process.env.DIRECT_URL ?? process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

const SEED_ROASTERS = [
  {
    name: "Onyx Coffee Lab",
    slug: "onyx-coffee-lab",
    description: "Pushing the boundaries of specialty coffee through science and transparency. Every bean is selected, profiled, and roasted with precision to unlock its full potential.",
    country: "United States",
    countryCode: "US",
    city: "Rogers, Arkansas",
    lat: 36.332,
    lng: -94.118,
    website: "https://onyxcoffeelab.com",
    shopUrl: "https://onyxcoffeelab.com/collections",
    instagram: "onyxcoffeelab",
    email: "hello@onyxcoffeelab.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Colombia", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    imageAlt: "Onyx Coffee Lab interior",
  },
  {
    name: "Tim Wendelboe",
    slug: "tim-wendelboe",
    description: "An espresso bar, roastery and coffee resource center focusing on quality. Founded by World Barista Champion Tim Wendelboe in Oslo.",
    country: "Norway",
    countryCode: "NO",
    city: "Oslo",
    lat: 59.916,
    lng: 10.752,
    website: "https://timwendelboe.no",
    shopUrl: "https://timwendelboe.no/shop",
    instagram: "timaborgen",
    email: "post@timwendelboe.no",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Colombia", "Kenya", "Ethiopia"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop",
    imageAlt: "Tim Wendelboe barista",
  },
  {
    name: "Square Mile",
    slug: "square-mile-coffee",
    description: "A multi-award winning specialty coffee roasting company founded in 2008 by James Hoffmann and Anette Moldvaer.",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    lat: 51.507,
    lng: -0.127,
    website: "https://squaremilecoffee.com",
    shopUrl: "https://squaremilecoffee.com/collections",
    instagram: "squaremilecoffee",
    email: "info@squaremilecoffee.com",
    certifications: ["DIRECT_TRADE", "ORGANIC", "SCA_MEMBER"],
    origins: ["Ethiopia", "Kenya", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Filter"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=600&fit=crop",
    imageAlt: "Square Mile coffee bags",
  },
  {
    name: "Hard Beans",
    slug: "hard-beans-opole",
    description: "Born in Opole, Hard Beans represents the pinnacle of Polish specialty coffee craftsmanship. Our approach is purely scientific yet deeply sensorial.",
    country: "Poland",
    countryCode: "PL",
    city: "Opole",
    lat: 50.675,
    lng: 17.921,
    website: "https://hardbeans.pl",
    shopUrl: "https://hardbeans.pl/sklep",
    instagram: "hardbeansroastery",
    email: "hello@hardbeans.com",
    certifications: ["DIRECT_TRADE", "SCA_MEMBER"],
    origins: ["Ethiopia", "Kenya", "Colombia"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=800&h=600&fit=crop",
    imageAlt: "Hard Beans roastery",
  },
  {
    name: "Gardelli Specialty",
    slug: "gardelli-specialty",
    description: "Founded by World Coffee Roasting Champion Rubens Gardelli. Dedicated to sourcing and roasting the finest specialty coffees.",
    country: "Italy",
    countryCode: "IT",
    city: "Forlì",
    lat: 44.222,
    lng: 12.040,
    website: "https://gardellicoffee.com",
    shopUrl: "https://gardellicoffee.com/shop",
    instagram: "gardellicoffee",
    email: "info@gardellicoffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Panama", "Colombia"],
    roastStyles: ["Light", "Medium"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop",
    imageAlt: "Gardelli roasting machine",
  },
  {
    name: "Assembly Coffee",
    slug: "assembly-coffee",
    description: "A roastery dedicated to the pursuit of independent coffee excellence. Sourcing directly from producers worldwide.",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    lat: 51.461,
    lng: -0.115,
    website: "https://assemblycoffee.co.uk",
    shopUrl: "https://assemblycoffee.co.uk/shop",
    instagram: "assemblycoffee",
    email: "hello@assemblycoffee.co.uk",
    certifications: ["DIRECT_TRADE", "ORGANIC"],
    origins: ["Ethiopia", "Colombia", "Rwanda"],
    roastStyles: ["Light", "Filter", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&h=600&fit=crop",
    imageAlt: "Assembly Coffee beans",
  },
  {
    name: "HAYB Coffee",
    slug: "hayb-coffee",
    description: "Warsaw-based specialty roaster known for innovative processing methods and direct relationships with farmers across Africa and South America.",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    lat: 52.229,
    lng: 21.012,
    website: "https://haybcoffee.pl",
    shopUrl: "https://haybcoffee.pl/shop",
    instagram: "haybcoffee",
    email: "hello@haybcoffee.pl",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Kenya", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop",
    imageAlt: "HAYB Coffee shop",
  },
  {
    name: "Coffee Proficiency",
    slug: "coffee-proficiency",
    description: "Kraków-based micro-roastery combining scientific precision with artisanal craft. Specializing in competition-grade lots.",
    country: "Poland",
    countryCode: "PL",
    city: "Kraków",
    lat: 50.064,
    lng: 19.944,
    website: "https://coffeeproficiency.com",
    shopUrl: "https://coffeeproficiency.com/shop",
    instagram: "coffeeproficiency",
    email: "info@coffeeproficiency.com",
    certifications: ["SCA_MEMBER", "DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Guatemala", "Peru"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&h=600&fit=crop",
    imageAlt: "Coffee Proficiency roastery",
  },
  {
    name: "The Nordic Roast",
    slug: "the-nordic-roast",
    description: "Oslo-based roastery focused on sustainability and light roasts that showcase terroir. Working directly with smallholder farmers.",
    country: "Norway",
    countryCode: "NO",
    city: "Oslo",
    lat: 59.930,
    lng: 10.738,
    website: "https://thenordicroast.no",
    shopUrl: "https://thenordicroast.no/shop",
    instagram: "nordicroast",
    email: "hello@thenordicroast.no",
    certifications: ["ORGANIC", "DIRECT_TRADE", "FAIR_TRADE"],
    origins: ["Ethiopia", "Kenya", "Rwanda"],
    roastStyles: ["Light"],
    status: "VERIFIED" as const,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&h=600&fit=crop",
    imageAlt: "Nordic Roast barista",
  },
  {
    name: "Dark Matter Labs",
    slug: "dark-matter-labs",
    description: "Chicago's experimental roastery pushing the boundaries of flavor. Known for bold, innovative blends and single origins.",
    country: "United States",
    countryCode: "US",
    city: "Chicago",
    lat: 41.878,
    lng: -87.629,
    website: "https://darkmatterlabs.com",
    shopUrl: "https://darkmatterlabs.com/shop",
    instagram: "darkmatterlabs",
    email: "hello@darkmatterlabs.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Colombia", "Ethiopia", "Indonesia"],
    roastStyles: ["Medium", "Dark", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&h=600&fit=crop",
    imageAlt: "Dark Matter Labs roasting",
  },
  {
    name: "Flora & Fauna",
    slug: "flora-and-fauna",
    description: "Melbourne-based ethical roastery committed to sustainable sourcing and community building through exceptional coffee.",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    lat: -37.813,
    lng: 144.963,
    website: "https://floraandfauna.coffee",
    shopUrl: "https://floraandfauna.coffee/shop",
    instagram: "florafaunacoffee",
    email: "hello@floraandfauna.coffee",
    certifications: ["ORGANIC", "FAIR_TRADE", "DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Brazil"],
    roastStyles: ["Light", "Medium", "Espresso"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&h=600&fit=crop",
    imageAlt: "Flora & Fauna coffee",
  },
  {
    name: "Sey Coffee",
    slug: "sey-coffee",
    description: "Clean, expressive, and terroir-driven coffee roasting from Brooklyn. Each coffee is roasted to express the unique character of its origin.",
    country: "United States",
    countryCode: "US",
    city: "Brooklyn",
    lat: 40.678,
    lng: -73.944,
    website: "https://www.seycoffee.com",
    shopUrl: "https://www.seycoffee.com/collections",
    instagram: "seycoffee",
    email: "hello@seycoffee.com",
    certifications: ["DIRECT_TRADE"],
    origins: ["Ethiopia", "Colombia", "Kenya", "Guatemala"],
    roastStyles: ["Light", "Filter"],
    status: "VERIFIED" as const,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop",
    imageAlt: "Sey Coffee cup",
  },
];

async function main() {
  console.log("Seeding database...");

  for (const roaster of SEED_ROASTERS) {
    const { imageUrl, imageAlt, ...data } = roaster;

    const created = await prisma.roaster.upsert({
      where: { slug: data.slug },
      update: data,
      create: {
        ...data,
        verifiedAt: new Date(),
        images: {
          create: {
            url: imageUrl,
            alt: imageAlt,
            order: 0,
            isPrimary: true,
          },
        },
      },
    });

    console.log(`  ${created.status === "VERIFIED" ? "✓" : "○"} ${created.name} (${created.slug})`);
  }

  console.log(`\nSeeded ${SEED_ROASTERS.length} roasters.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
