/**
 * Maps common country names to ISO 3166-1 alpha-2 codes.
 * Used by registration form to auto-resolve countryCode.
 */
const COUNTRY_MAP: Record<string, string> = {
  "australia": "AU",
  "austria": "AT",
  "belgium": "BE",
  "brazil": "BR",
  "canada": "CA",
  "chile": "CL",
  "china": "CN",
  "colombia": "CO",
  "costa rica": "CR",
  "czech republic": "CZ",
  "czechia": "CZ",
  "denmark": "DK",
  "ecuador": "EC",
  "el salvador": "SV",
  "ethiopia": "ET",
  "finland": "FI",
  "france": "FR",
  "germany": "DE",
  "greece": "GR",
  "guatemala": "GT",
  "honduras": "HN",
  "hungary": "HU",
  "india": "IN",
  "indonesia": "ID",
  "ireland": "IE",
  "israel": "IL",
  "italy": "IT",
  "japan": "JP",
  "kenya": "KE",
  "mexico": "MX",
  "netherlands": "NL",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "norway": "NO",
  "panama": "PA",
  "peru": "PE",
  "philippines": "PH",
  "poland": "PL",
  "portugal": "PT",
  "romania": "RO",
  "rwanda": "RW",
  "south africa": "ZA",
  "south korea": "KR",
  "spain": "ES",
  "sweden": "SE",
  "switzerland": "CH",
  "taiwan": "TW",
  "thailand": "TH",
  "turkey": "TR",
  "türkiye": "TR",
  "uganda": "UG",
  "united arab emirates": "AE",
  "uae": "AE",
  "united kingdom": "GB",
  "uk": "GB",
  "united states": "US",
  "usa": "US",
  "vietnam": "VN",
  "yemen": "YE",
};

export function resolveCountryCode(country: string): string {
  return COUNTRY_MAP[country.toLowerCase().trim()] ?? "";
}
